name: Build and Release Obsidian Plugin

on:
  push:
    tags:
      - "v*"
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Package plugin
        run: |
          mkdir release
          cp manifest.json dist/main.js styles.css release/ || true
          cd release && zip -r ../plugin.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: plugin.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
